### ISSUE TITLE
BlacklistBanManager

### ISSUE THREAD

**Issue by verleihernix** [HyperGaming99/Zyper#4]
Descriptions (/**/*) im Blacklistmanager sind deutsch (sollten glaub Englisch sein) warum sieht das so chatgpt aus 😭

**Comment by verleihernix** [comment]
halt wer sagt "Discord.js-Client Instanz" 💀

**Comment by verleihernix** [comment]
Und halt overall sieht man da keine wirkliche Funktion drin, ist halt basically nur ein Array Manager, richtige Funktionalität muss man selber implementieren

**Comment by HyperGaming99** [comment]
> halt wer sagt "Discord.js-Client Instanz" 💀

Das ist doch ganz normal

**Comment by HyperGaming99** [comment]
> Descriptions (/**/*) im Blacklistmanager sind deutsch (sollten glaub Englisch sein)
hab alles jetzt auf englisch gemacht
